FizzBuzzProject/FizzBuzzProject/Models/FizzBuzzViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace FizzBuzzProject.Models
{
    public class FizzBuzzViewModel
    {

        [Range(1, 1000, ErrorMessage = "Value should be between 1 and 1000")]
        [Required(ErrorMessage = "Please Enter a Value")]
        public int? UserInput { get; set; }
        public IPagedList<String> FizzBuzzNumbers { get; set; }
    }
}

FizzBuzzProject/FizzBuzzProject/Controllers/FizzBuzzController.cs
using FizzBuzzProject.Models;
using FizzBuzzProject.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace FizzBuzzProject.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService service;

        public FizzBuzzController(IFizzBuzzService service)
        {
            this.service = service;
        }


        [HttpGet]
        public ViewResult Index(int UserInput, int? page)
        {
            if (UserInput == 0) return View();
            FizzBuzzViewModel fizzBuzzViewModel = new() { UserInput = UserInput };
            var numbers =
                service.GetFizzBuzzNumbers(UserInput);
            var pageNumber = page ?? 1;
            fizzBuzzViewModel.FizzBuzzNumbers = numbers.ToPagedList(pageNumber, 20);
            return View("Index", fizzBuzzViewModel);

        }
        [HttpPost]
        public IActionResult Index(FizzBuzzViewModel fizzBuzzViewModel)
        {
            if (ModelState.IsValid == false)
            {
                return View();
            }
            return RedirectToAction("Index", new { fizzBuzzViewModel.UserInput, page = 1 });

        }
    }
}

FizzBuzzProject/FizzBuzzProject/Views/FizzBuzz/Index.cshtml
@model FizzBuzzViewModel
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Fizz Buzz";
}
<form asp-controller="FizzBuzz" asp-action="index" method="post" class="">
    <div class="form-group row container col-sm-12 text-center">
        <label asp-for="UserInput" class=" col-form-label col-sm-3">Enter a Number</label>
        <div class="col-sm-5 col">
            <input asp-for="UserInput" class="form-control" placeholder="Integer">
        </div>
        <button type="submit" class="btn btn-primary col-sm-1">Enter</button>
        <span asp-validation-for="UserInput" class="text-danger text-center col-sm-3"></span>
    </div>

</form>
<hr>
@{ if (Model != null && Model.FizzBuzzNumbers != null)
    {
        <div class="container ">

            @foreach (var s in Model.FizzBuzzNumbers)
            {
                <h4 class="@s">@s</h4>}

        </div>
        <div class="pagination h4" style="margin:auto;width:0%;">
            @Html.PagedListPager((IPagedList)Model.FizzBuzzNumbers, page =>
                        Url.Action("Index", new { page, Model.UserInput }))
        </div>

    }
}

FizzBuzzProject/FizzBuzzProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <h1 class="text-center">FIZZBUZZ PROJECT</h1>
    <div>
        @RenderBody()
    </div>
</body>
</html>